import PortfolioHeader from "@/components/Portfolio/PortfolioHeader"
import "./portfolio.css"

export const metadata = {
  title : `포트폴리오`,
  description : `Generated by croo12`,
}

const PortfolioLayout = ({
  children,
} : {
  children: React.ReactNode
}) => {

  return (
    <div className="portfolio-page">
      <PortfolioHeader />
      <div className="portfolio-main">
        {children}
      </div>
    </div>
  )
}

export default PortfolioLayout